In [1]:
import pandas as pd
from datetime import datetime

df = pd.read_csv("C:/Users/aksha/Documents/Github Datasets/UK Online Retail Data/Dataset.csv")
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'], errors='coerce')
df = df.iloc[:, :-1]

df

C:\Users\aksha\anaconda3\lib\site-packages\pandas\core\computation\expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.7.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\aksha\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.2' currently installed).
  from pandas.core import (

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Market Type
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01,2.55,17850.0,United Kingdom,15.30,Domestic
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01,3.39,17850.0,United Kingdom,20.34,Domestic
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01,2.75,17850.0,United Kingdom,22.00,Domestic
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01,3.39,17850.0,United Kingdom,20.34,Domestic
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01,3.39,17850.0,United Kingdom,20.34,Domestic
...,...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09,0.85,12680.0,France,10.20,International
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09,2.10,12680.0,France,12.60,International
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09,4.15,12680.0,France,16.60,International
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09,4.15,12680.0,France,16.60,International
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09,4.95,12680.0,France,14.85,International

In [2]:
df['LatestInvoiceDate'] = df[df['Quantity'] > 0].groupby('CustomerID')['InvoiceDate'].transform('max')
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Market Type,LatestInvoiceDate
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01,2.55,17850.0,United Kingdom,15.30,Domestic,2010-12-02
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01,3.39,17850.0,United Kingdom,20.34,Domestic,2010-12-02
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01,2.75,17850.0,United Kingdom,22.00,Domestic,2010-12-02
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01,3.39,17850.0,United Kingdom,20.34,Domestic,2010-12-02
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01,3.39,17850.0,United Kingdom,20.34,Domestic,2010-12-02
...,...,...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09,0.85,12680.0,France,10.20,International,2011-12-09
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09,2.10,12680.0,France,12.60,International,2011-12-09
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09,4.15,12680.0,France,16.60,International,2011-12-09
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09,4.15,12680.0,France,16.60,International,2011-12-09
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09,4.95,12680.0,France,14.85,International,2011-12-09

In [3]:
reference_date = datetime(2011, 12, 10)

df['Recency'] = (reference_date - df['LatestInvoiceDate']).dt.days

df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Market Type,LatestInvoiceDate,Recency
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01,2.55,17850.0,United Kingdom,15.30,Domestic,2010-12-02,373.0
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01,3.39,17850.0,United Kingdom,20.34,Domestic,2010-12-02,373.0
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01,2.75,17850.0,United Kingdom,22.00,Domestic,2010-12-02,373.0
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01,3.39,17850.0,United Kingdom,20.34,Domestic,2010-12-02,373.0
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01,3.39,17850.0,United Kingdom,20.34,Domestic,2010-12-02,373.0
...,...,...,...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09,0.85,12680.0,France,10.20,International,2011-12-09,1.0
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09,2.10,12680.0,France,12.60,International,2011-12-09,1.0
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09,4.15,12680.0,France,16.60,International,2011-12-09,1.0
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09,4.15,12680.0,France,16.60,International,2011-12-09,1.0
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09,4.95,12680.0,France,14.85,International,2011-12-09,1.0

In [4]:
frequency = (df[df['Quantity'] > 0]
             .groupby('CustomerID')['InvoiceNo']
             .count()
             .reset_index()
             .rename(columns={'InvoiceNo': 'Frequency'}))

# Merge Frequency back to the main dataframe
df = df.merge(frequency, on='CustomerID', how='left')

df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Market Type,LatestInvoiceDate,Recency,Frequency
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01,2.55,17850.0,United Kingdom,15.30,Domestic,2010-12-02,373.0,297.0
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01,3.39,17850.0,United Kingdom,20.34,Domestic,2010-12-02,373.0,297.0
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01,2.75,17850.0,United Kingdom,22.00,Domestic,2010-12-02,373.0,297.0
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01,3.39,17850.0,United Kingdom,20.34,Domestic,2010-12-02,373.0,297.0
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01,3.39,17850.0,United Kingdom,20.34,Domestic,2010-12-02,373.0,297.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09,0.85,12680.0,France,10.20,International,2011-12-09,1.0,52.0
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09,2.10,12680.0,France,12.60,International,2011-12-09,1.0,52.0
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09,4.15,12680.0,France,16.60,International,2011-12-09,1.0,52.0
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09,4.15,12680.0,France,16.60,International,2011-12-09,1.0,52.0
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09,4.95,12680.0,France,14.85,International,2011-12-09,1.0,52.0

In [5]:
monetary = (df.groupby('CustomerID')['TotalPrice']
             .sum()
             .reset_index()
             .rename(columns={'TotalPrice': 'Monetary'}))

# Merge Monetary back to the main dataframe
df = df.merge(monetary, on='CustomerID', how='left')

df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Market Type,LatestInvoiceDate,Recency,Frequency,Monetary
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01,2.55,17850.0,United Kingdom,15.30,Domestic,2010-12-02,373.0,297.0,5288.63
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01,3.39,17850.0,United Kingdom,20.34,Domestic,2010-12-02,373.0,297.0,5288.63
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01,2.75,17850.0,United Kingdom,22.00,Domestic,2010-12-02,373.0,297.0,5288.63
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01,3.39,17850.0,United Kingdom,20.34,Domestic,2010-12-02,373.0,297.0,5288.63
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01,3.39,17850.0,United Kingdom,20.34,Domestic,2010-12-02,373.0,297.0,5288.63
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09,0.85,12680.0,France,10.20,International,2011-12-09,1.0,52.0,862.81
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09,2.10,12680.0,France,12.60,International,2011-12-09,1.0,52.0,862.81
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09,4.15,12680.0,France,16.60,International,2011-12-09,1.0,52.0,862.81
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09,4.15,12680.0,France,16.60,International,2011-12-09,1.0,52.0,862.81
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09,4.95,12680.0,France,14.85,International,2011-12-09,1.0,52.0,862.81

In [6]:
df.to_csv("C:/Users/aksha/Documents/Github Datasets/UK Online Retail Data/dataset_updated.csv", 
          index=False,           # Don't include the row index (0, 1, 2...)
          encoding='ISO-8859-1')

In [7]:
rfm = pd.read_csv("C:/Users/aksha/Documents/Github Datasets/UK Online Retail Data/RMF_Dataset.csv")
rfm

      CustomerID  Recency  Frequency  Monetary
0          12791      374          2       193
1          13065      374         14       206
2          13747      374          1        80
3          14142      374         22       312
4          14237      374          9       161
...          ...      ...        ...       ...
4334       17428        1        328     17078
4335       17490        1         76      1927
4336       17581        1        440     10736
4337       17754        1         92      1740
4338       18102        1        431    256438

[4339 rows x 4 columns]

In [8]:
# Recency: lower is better so scoring is INVERTED (label 5 goes to lowest values)
rfm['R_Score'] = pd.qcut(rfm['Recency'], q=5, labels=[5, 4, 3, 2, 1])

# Frequency: higher is better so scoring is NORMAL
rfm['F_Score'] = pd.qcut(rfm['Frequency'].rank(method='first'), q=5, labels=[1, 2, 3, 4, 5])

# Monetary: higher is better so scoring is NORMAL
rfm['M_Score'] = pd.qcut(rfm['Monetary'], q=5, labels=[1, 2, 3, 4, 5])

# Combine into a single RFM score string e.g. "5-4-3"
rfm['RFM_Segment'] = (rfm['R_Score'].astype(str) + '-' +
                      rfm['F_Score'].astype(str) + '-' +
                      rfm['M_Score'].astype(str))

# Composite numeric score (sum, range 3–15)
rfm['RFM_Score'] = (rfm['R_Score'].astype(int) +
                    rfm['F_Score'].astype(int) +
                    rfm['M_Score'].astype(int))

In [9]:
rfm

,CustomerID,Recency,Frequency,Monetary,R_Score,F_Score,M_Score,RFM_Segment,RFM_Score
0,12791,374,2,193,1,1,1,1-1-1,3
1,13065,374,14,206,1,1,1,1-1-1,3
2,13747,374,1,80,1,1,1,1-1-1,3
3,14142,374,22,312,1,2,2,1-2-2,5
4,14237,374,9,161,1,1,1,1-1-1,3
...,...,...,...,...,...,...,...,...,...
4334,17428,1,328,17078,5,5,5,5-5-5,15
4335,17490,1,76,1927,5,4,4,5-4-4,13
4336,17581,1,440,10736,5,5,5,5-5-5,15
4337,17754,1,92,1740,5,4,4,5-4-4,13
4338,18102,1,431,256438,5,5,5,5-5-5,15

In [10]:
# Cast columns ONCE before applying
rfm['R_Score'] = rfm['R_Score'].astype(int)
rfm['F_Score'] = rfm['F_Score'].astype(int)
rfm['M_Score'] = rfm['M_Score'].astype(int)
rfm['FM_Score'] = ((rfm['F_Score'] + rfm['M_Score']) / 2).round().astype(int).clip(1, 5)

def assign_segment(r, f, m):

    # Champions — recently active, highly frequent, high spenders
    if r >= 4 and f >= 4 and m >= 4:
        return 'Champions'

    # Can't Lose Them — were high value but have gone very quiet
    # Check EARLY before other low-recency segments absorb them
    elif r <= 2 and f >= 4 and m >= 4:
        return "Can't Lose Them"

    # At Risk — used to buy reasonably well but recency is poor
    elif r <= 2 and f >= 3 and m >= 3:
        return 'At Risk'

    # Loyal Customers — frequent and high spend, still somewhat recent
    elif r >= 3 and f >= 3 and m >= 3:
        return 'Loyal Customers'

    # New Customers — very recent but only bought once or twice
    elif r >= 4 and f <= 2:
        return 'New Customers'

    # Promising — recent, some frequency, but spend not yet high
    elif r >= 3 and f >= 2 and m <= 3:
        return 'Promising'

    # Potential Loyalist — recent, low frequency, moderate spend
    elif r >= 3 and f <= 2 and m >= 2:
        return 'Potential Loyalist'

    # Need Attention — mid recency, frequency and spend declining
    elif r == 3 and f <= 3 and m <= 3:
        return 'Need Attention'

    # About to Sleep — recency fading, low engagement across the board
    elif r == 2 and f <= 3 and m <= 3:
        return 'About to Sleep'

    # Hibernating — everything low, effectively churned
    else:
        return 'Hibernating'

# Now x['R_Score'] is already an int scalar — no .astype() needed
rfm['Segment'] = rfm.apply(
    lambda x: assign_segment(x['R_Score'], x['F_Score'], x['M_Score']),
    axis=1
)

In [11]:
# Count customers per segment for annotation
segment_counts = rfm['Segment'].value_counts()
print(segment_counts)

Segment
Champions             924
Loyal Customers       811
Hibernating           797
About to Sleep        435
Promising             372
New Customers         351
At Risk               305
Can't Lose Them       190
Need Attention         88
Potential Loyalist     66
Name: count, dtype: int64

In [12]:
rfm

,CustomerID,Recency,Frequency,Monetary,R_Score,F_Score,M_Score,RFM_Segment,RFM_Score,FM_Score,Segment
0,12791,374,2,193,1,1,1,1-1-1,3,1,Hibernating
1,13065,374,14,206,1,1,1,1-1-1,3,1,Hibernating
2,13747,374,1,80,1,1,1,1-1-1,3,1,Hibernating
3,14142,374,22,312,1,2,2,1-2-2,5,2,Hibernating
4,14237,374,9,161,1,1,1,1-1-1,3,1,Hibernating
...,...,...,...,...,...,...,...,...,...,...,...
4334,17428,1,328,17078,5,5,5,5-5-5,15,5,Champions
4335,17490,1,76,1927,5,4,4,5-4-4,13,4,Champions
4336,17581,1,440,10736,5,5,5,5-5-5,15,5,Champions
4337,17754,1,92,1740,5,4,4,5-4-4,13,4,Champions
4338,18102,1,431,256438,5,5,5,5-5-5,15,5,Champions

In [13]:
rfm.to_csv("C:/Users/aksha/Documents/Github Datasets/UK Online Retail Data/rfm_updated.csv", 
          index=False,           # Don't include the row index (0, 1, 2...)
          encoding='ISO-8859-1')